### ISSUE TITLE
抖动太厉害咯

### ISSUE THREAD

**Issue by DingMr** [cyynf/MarqueeView#1]
抖得不行

**Comment by cyynf** [comment]
看看你的使用方法

**Comment by DingMr** [comment]
### 我是通过WindowManager将MarqueeTextView添加到窗口展示
`            if (mMarqueeTextView == null) {
                mMarqueeTextView = new MarqueeTextView(context);
                mMarqueeTextView.setFocusable(false);
                mMarqueeTextView.setIncludeFontPadding(false);
                mMarqueeTextView.setTextSize(36f);
                mMarqueeTextView.setPadding(0, 0, 0, 36);
                mMarqueeTextView.setTextColor(Color.WHITE);
                mMarqueeTextView.setBackgroundColor(context.getResources().getColor(R.color.transparent));
                mMarqueeTextView.setText("showText");
AssetManager assm = getAssets();
Typeface tf = Typeface.createFromAsset(assm, "webfont.ttf");
        marqueeTextView.setTypeface(tf);
wm.addView(mMarqueeTextView, layoutParams);
                wm.updateViewLayout(mMarqueeTextView, layoutParams);
            }`

**wm的设置**
`            if (wm == null) {
                wm = (WindowManager) context.getSystemService(Context.WINDOW_SERVICE);
                layoutParams = new WindowManager.LayoutParams();
                layoutParams.width = WindowManager.LayoutParams.MATCH_PARENT;
                layoutParams.height = WindowManager.LayoutParams.WRAP_CONTENT;
                layoutParams.alpha = 1f;
                layoutParams.format = PixelFormat.TRANSLUCENT;
                if (Build.VERSION.SDK_INT >= 26) {
                    layoutParams.type = WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY;
                } else {
                    layoutParams.type = WindowManager.LayoutParams.TYPE_SYSTEM_ALERT
                            | WindowManager.LayoutParams.TYPE_SYSTEM_OVERLAY;
                }
                layoutParams.flags = WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL
                        | WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE;
                layoutParams.gravity = Gravity.CENTER | Gravity.BOTTOM;
            }`

**Comment by DingMr** [comment]
![image](https://user-images.githubusercontent.com/24539859/84970702-cab9e500-b14d-11ea-82ec-718d5b497646.png)

**Comment by cyynf** [comment]
surfaceview不能这么用的，建议不要使用windowmanage添加

**Comment by DingMr** [comment]
(●ˇ∀ˇ●) 谢谢！我想想其他办法
